apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    jsonData:
      version: Flux
      organization: layzspa
      defaultBucket: spa
      tlsSkipVerify: true
    secureJsonData:
      token: lhSO_AUMJs9WExMMofExAhErZS52GxSSZyooL3u_zXGWDOZxUvhz9ovH8HEMISa3HHlaizSwEPgVGKarwZ08pA==
