; Local PlatformIO configuration overrides
; This file is used to override settings in platformio.ini without modifying the main config
; Place your local/personal configuration here (e.g., custom upload settings, board settings, etc.)
; This file is git-ignored and should not be committed to the repository


[env:nodemcuv2]
 upload_protocol = espota
 upload_port = layzspa.local
 upload_flags = 
     --auth=esp8266
build_flags = 
    -DFILTER_6W_SPIKES=3 ;Comment out to disable. 0=All CIO messages needs to be sent twice before accepting them. 1 or higher: Set to number of consecutive readings must occur before accepting a change in the state of flipflop entities (pump, heat etc).
    ; -DLOCKTOC ;Make sure the pump is set to Celsius or else the antifreeze etc won't work. Please disable the UNIT button from the SPA CONFIG page.
    ; -DLOCKTOF ;Make sure the pump is set to Fahrenheit or else the antifreeze etc won't work. Please disable the UNIT button from the SPA CONFIG page.
    ; -DBWC_DEBUGGING=BWC_DEBUG_OUTPUT_OFF
    -DBWC_DEBUGGING=BWC_DEBUG_OUTPUT_SERIAL
    ; -DBWC_DEBUGGING=BWC_DEBUG_OUTPUT_FILE
    -DBWC_SPRINKLE_YIELDS ;Yeah yeah, some call it a band aid but you do what you gotta do, right?
	-DWEBSOCKETS_NETWORK_TYPE="NETWORK_ESP8266_ASYNC"
    -DWEBSOCKETS_SAVE_RAM
    ; -DDEBUG_ESP_PORT=Serial ; adds around 800 bytes to iram (.text1)
    ; -D BUILDTIME=$UNIX_TIME
    ; -DDEBUG_ESP_SSL
    ; -DDEBUG_ESP_TLS_MEM
    ; -DDEBUG_ESPHTTP_CLIENT
    ; -DDEBUG_ESP_HTTP_UPDATE
    ; -DDEBUG_ESP_OOM
    ; -DDEBUG_ESP_MMU
    ; -include "umm_malloc/umm_malloc_cfg.h"
	; -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48
    -D PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
    ; -D PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM32_SECHEAP_NOTSHARED
    ; -D PIO_FRAMEWORK_ARDUINO_MMU_CUSTOM
    ; -D MMU_IRAM_SIZE=0xC000
    ; -D MMU_ICACHE_SIZE=0x4000
    ; -D MMU_IRAM_HEAP    
    -DVTABLES_IN_FLASH
    ; -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
    ; -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    ; -D BEARSSL_SSL_BASIC
    ; -Wl,-Map,output.map
upload_speed = 921600 ; enable if you device are capable
